spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mariadb
    driver-class-name: org.mariadb.jdbc.Driver
    username: mariadb
    password: password
logging:
  level:
    org.hibernate.SQL: debug